config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources "entries"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end
  def show
    @entry = Entry.find(params["id"])
  end
  def create
    entry_params = params["entry"].permit("title", "date", "contents")
    entry = Entry.create(entry_params)
    redirect_to(entry_path(entry))
  end
  def edit
    @entry = Entry.find(params["id"])
  end
  def update
    entry_params = params["entry"].permit("title", "date", "contents")
    entry = Entry.find(params["id"])
    entry.update(entry_params)
    redirect_to(entry_path(entry))
  end
  def destroy
    entry = Entry.destroy(params["id"])
    redirect_to(entries_path, notice: 'Entry was successfully destroyed.')
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @webside =[
    ["https://unsplash.com", "Unsplash"],
    ["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
    ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/edit.html.erb
<%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("date") %></p>
  <p><%= form.text_field("date") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<button><%= link_to("Back to this entry", entry_path(@entry)) %></button>
<button><%= link_to("Back to all entries", entries_path) %></button>

app/views/entries/index.html.erb
<h1>Travels</h1>
<div>
  <% for entry in @entries %>
      <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
      <p><%= entry.date %></p>
      <p><%= entry.contents %></p>
  <% end %>
</div>
<button>
  <%= link_to("New entry", new_entry_path) %>
</button>
<button>
  <%= link_to("Back to favourites", root_path) %>
</button>

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("date") %></p>
  <p><%= form.text_field("date") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<button><%= link_to("Back to all entries", entries_path) %></button>

app/views/entries/show.html.erb
<h1><%= link_to("Travels", entries_path) %></h1>
<div>
  <h2><%= @entry.title %></h2>
  <p><%= @entry.date %></p>
  <p><%= @entry.contents %></p>
</div>
  <button><%= link_to("Back to all entries", entries_path) %></button>
  <button><%= link_to("Edit this entry", edit_entry_path(@entry)) %></button>
  <button><%= link_to("Delete this entry", @entry, data:{confirm: 'Are you sure?'}, method: :delete) %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travels Diary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>My Travels Diary</h1>
<div>
<h1>My favourite websites</h1>
  <% for url, name in @webside %>
    <li><a target="_blank" href="<%= url %>"><%= name %></a></li>
  <% end %>
</div>
<button>
  <%= link_to("Go to entries", entries_path) %>
</button>
<img src="https://images.unsplash.com/photo-1476114817938-a20b64783c7d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=fd7c4570f2fb357573e3fed72788998b&auto=format&fit=crop&w=1047&q=80'" alt="Mountains">